require('settings')
require('keymaps')
require('plugins.packer')
require('plugins.colorscheme')
require('plugins.nvim-treesitter')
require('plugins.nvim-tree')
require('plugins.autopairs')
require('plugins.completion')
require('plugins.lsp')
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.comment")
require("plugins.presence")

